COVID_QUES_SHEET = 0
SPQ_QUES_SHEET = 1
DEMOGRAPHIC_QUES_SHEET = 2
QUALITY_QUES_SHEET = 3
FATIGUE_QUES_SHEET = 4
QUESTION_SHEET = [COVID_QUES_SHEET, SPQ_QUES_SHEET, DEMOGRAPHIC_QUES_SHEET, QUALITY_QUES_SHEET, FATIGUE_QUES_SHEET]
QUESTIONAIRE_TYPE = ['Covid', 'SPQ', "Demographic", "Quality", "Fatigue"]
