version: '3.8'
services:
  userdb:
    container_name: 'userdb'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'userdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    #    expose:
    #      # Opens port 3306 on the container
    #      - '3306'
    #      # Where our data will be persisted
    volumes:
      - ./data/userdb:/var/lib/mysql

  happyagaindb:
    container_name: 'happyagaindb'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'happyagaindb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      #    expose:
      #      # Opens port 3306 on the container
      #      - '3307'
      # Where our data will be persisted
    volumes:
      - ./data/happyagaindb:/var/lib/mysql
